import { Container, Grid } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Toolbar from '../src//components/Toolbar';
import Navigation from '../src/components/Navigation';
import WaveAnimatedEmoji from '../src/components/WaveAnimatedEmoji';
import { Profile } from '../src/sections/home';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Toolbar />
				<Navigation />
				<Container>
					<Grid container>
						<Grid
							item
							sm={12}
							md={3}
							sx={{ mt: { xs: 0, md: -5 }, px: 2, pt: { xs: 5, md: 0 } }}
						>
							<Profile />
						</Grid>
						<Grid item sm={12} md={9} sx={{ pt: 2, px: 2 }}>
							<WaveAnimatedEmoji>👋</WaveAnimatedEmoji>
						</Grid>
					</Grid>
				</Container>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
