import { Container, Grid } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Toolbar from '../src//components/Toolbar';
import Navigation from '../src/components/Navigation';
import { Education, Experience, Profile } from '../src/sections/home';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Toolbar />
				<Navigation />
				<Container>
					<Grid container>
						<Grid
							item
							sm={12}
							md={3}
							sx={{ mt: { xs: 0, md: -5 }, px: 2, pt: { xs: 5, md: 0 } }}
						>
							<Profile />
						</Grid>
						<Grid item sm={12} md={9} sx={{ pt: 2, px: 2 }}>
							<Experience />
							<Education />
						</Grid>
					</Grid>
				</Container>
			</main>
		</div>
	);
};

export default Home;
