name: Lint Pull Request

on: pull_request

jobs:
    lint_pr:
        runs-on: ubuntu-latest

        steps:
            # Checkout
            - uses: actions/checkout@v2

            # Node Install
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18.13.0'

            # Npm Install Yarn
            - name: Install specific yarn
              run: npm install --global yarn@1.22.0

            # Yarn Install
            - name: Install dependencies
              run: yarn install

            # Yarn Lint
            - name: Lint source files
              run: yarn run lint

            # Yarn Prettier check
            - name: Run prettier check
              run: yarn run format-check
